spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver


jpa:
  hibernate:
    hbm2ddl:
      auto: update
  dialect: org.hibernate.dialect.MySQLDialect
  show-sql: true
  properties:
    spring.jackson.date-format: yyyy-MM-dd HH:mm  # 配置日期格式
    spring.jackson.serialization.write-dates-as-timestamps: false  # 禁用时间戳格式

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 指定相应接口对应的xml文件所在目录
  type-aliases-package: wuhao.springboot.middle.entity  # 实体类所在包
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰式命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印日志